_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://auth-service:8000
    routes:
      - name: auth-routes
        paths:
          - /api/auth
          - /api/accounts
          - /api/schema
          - /api/docs
        strip_path: false

  - name: user-service
    url: http://user-service:8000
    routes:
      - name: user-routes
        paths:
          - /api/users
          - /api/profiles
        strip_path: false

  - name: class-service
    url: http://class-service:8000
    routes:
      - name: class-routes
        paths:
          - /api/classes
          - /api/schema
          - /api/docs
        strip_path: false

  - name: subject-service
    url: http://subject-service:8000
    routes:
      - name: subject-routes
        paths:
          - /api/subjects
        strip_path: false

  - name: grade-service
    url: http://grade-service:8000
    routes:
      - name: grade-routes
        paths:
          - /api/grades
        strip_path: false

  - name: schedule-service
    url: http://schedule-service:8000
    routes:
      - name: schedule-routes
        paths:
          - /api/schedules
        strip_path: false

  - name: messaging-service
    url: http://messaging-service:8000
    routes:
      - name: messaging-routes
        paths:
          - /api/messaging
        strip_path: false

  - name: live-service
    url: http://live-service:8000
    routes:
      - name: live-routes
        paths:
          - /api/live
        strip_path: false

  - name: live-ws
    url: http://live-service:8000
    routes:
      - name: live-ws-routes
        paths:
          - /ws/live
        strip_path: false

  - name: complaint-service
    url: http://complaint-service:8000
    routes:
      - name: complaint-routes
        paths:
          - /api/reclamations
        strip_path: false

  - name: billing-service
    url: http://billing-service:8000
    routes:
      - name: billing-routes
        paths:
          - /api/billing
        strip_path: false

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
      credentials: true
